task:
  timeout_in: 5m
  container:
    image: gcc:latest
  env:
    CLICOLOR_FORCE:
    ASAN_OPTIONS: detect_leaks=0
    LD_LIBRARY_PATH: /usr/local/lib
  bootstrap_script:
    - git clone https://github.com/inobulles/bob --depth 1 --branch v0.2.16
    - ( cd bob && sh bootstrap.sh && .bootstrap/bob install )
  build_script:
    - bob install
  test_script:
    - sh tests/levels/test.sh
    - sh tests/filter/test.sh
  amd64_artifacts:
    path: ".bob/prefix/*"

task:
  timeout_in: 5m
  arm_container:
    image: gcc:latest
  env:
    CLICOLOR_FORCE:
    ASAN_OPTIONS: detect_leaks=0
    LD_LIBRARY_PATH: /usr/local/lib
  bootstrap_script:
    - git clone https://github.com/inobulles/bob --depth 1 --branch v0.2.16
    - ( cd bob && sh bootstrap.sh && .bootstrap/bob install )
  build_script:
    - bob install
  test_script:
    - sh tests/levels/test.sh
    - sh tests/filter/test.sh
  amd64_artifacts:
    path: ".bob/prefix/*"
